# spring.application.name=lms-backend
spring:
  application:
    name: lms-backend
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: 2003

  mail:
    host: smtp.gmail.com
    port: 587
    username: eduplatform2222@gmail.com
    password: cmlvlevoyywkjarl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8090

#  cmlv levo yywk jarl

